import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="utf-8"/>

      <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>

      <meta
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
        name="viewport"
      />

      <title>Homepage | Christian Dechant</title>

      <meta property="og:title" content="Homepage | Christian Dechant"/>

      <meta property="og:locale" content="en_US"/>

      <link
        rel="canonical"
        href="//"
      />

      <meta
        property="og:url"
        content="//"
      />

      <meta
        name="description"
        content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
      />

      <link rel="icon" type="image/png" href="/assets/img/favicon.png"/>

      <meta name="theme-color" content="#5540af"/>

      <meta property="og:site_name" content="Atom Template"/>

      <meta property="og:image" content="//assets/img/social.jpg"/>

      <meta name="twitter:card" content="summary_large_image"/>

      <meta name="twitter:site" content="@tailwindmade"/>
{/*
      <link
        crossOrigin="crossorigin"
        href="https://fonts.gstatic.com"
        rel="preconnect"
      />

      <link
        as="style"
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&family=Raleway:wght@400;500;600;700&display=swap"
        rel="preload"
      />

      <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&family=Raleway:wght@400;500;600;700&display=swap"
        rel="stylesheet"
      />

      <link
        href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
        rel="stylesheet"
      />*/}

      <link
        crossOrigin="anonymous"
        href="globals.css"
        media="screen"
        rel="stylesheet"
      />

      {/*<script
        defer
        src="https://unpkg.com/@alpine-collective/toolkit@1.0.0/dist/cdn.min.js"
      ></script>

      <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>*/}


    </head>
    <body
      className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }
      x-data="{ mobileMenu: false }"
    >
    { children }
    </body>
    </html>
  );
}
