name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="InTerestedOWL" 
          repo_name="YAML_Infrastructure"  
          event_type="trigger-workflow" 
          service="christiandechant"
          version="${{ github.sha }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/InTerestedOWL/YAML_Infrastructure/dispatches \
            -d '{"event_type": "trigger-workflow", "client_payload": {"service": "christiandechant", "version": "${{ github.sha }}", "unit": false, "integration": true}}'